# Generated by Django 4.0.4 on 2022-05-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Slug',
            new_name='slug',
        ),
    ]
